sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t damienpond/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true damienpond/docker-react npm run test


